### PR TITLE
Fix wrong example in README.

### PR DESCRIPTION
**Pull request by gedex**
The returned method should be Response object instead of Request object.

### CODE REVIEW

**Comment by claudiosmweb** [comment]
I just want keep `wcapi` because I used it as example in line 34

**Comment by gedex** [comment]
Your `wcapi` example in line 34 is perect. I was referring example that follows after that, for instance:

```
>>> wcapi.get("products")
>>> wcapi.status_code
200
```

would raise `AttributeError` because `API` object doesn't have `status_code` attribute.

**Comment by claudiosmweb** [comment]
But why you change the examples? :p

```
-    >>> wcapi.status_code
+    >>> r = wcapi.get("products")
```

**Comment by claudiosmweb** [comment]
Ohh yeah xD
Now I get!

**Pull request merged**
