### PR TITLE
Add option to auth with https with query param

### PR DESCRIPTION
**Pull request by bertonha**
Some https stores lost auth header them need to send it with query params

http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

### CODE REVIEW

**Comment by canassa** [comment]
Any update on this? I also need this feature :smile:

**Comment by claudiosmweb** [comment]
You can just pass as query string in your URL.

**Comment by bertonha** [comment]
At least you could have said thanks two years later you finally realized you would be able to use my advice. The timespan of your reaction couldn't be longer I assume. Good luck.

**Comment by zslusnys** [comment]
So much for a developer that appreciates colleagues work. Thanks @bertonha for the contribution, lets make this api great again.

**Pull request closed without merging**
